apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: nt77mgr3o-nodejs 
  janus-idp.io/tekton: nt77mgr3o-nodejs
  backstage.io/kubernetes-id: nt77mgr3o-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: nt77mgr3o-nodejs
resources:
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml